common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('upload/', include('upload.urls')),
    path('onlineclass/', include('onlineclass.urls')),
]

onlineclass/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "onlineclass"

urlpatterns = [
    path("original_video/<int:doc_id>/", views.show_origianl_video, name="show_origianl_video"),
    path("pdf_download/<int:doc_id>/", views.download_pdf, name="download_pdf"),
    path("commentor/<int:doc_id>/", views.execute_commentor, name="execute_commentor"),
    path("txt_download/<int:doc_id>/", views.download_txt, name="download_txt"),
]

upload/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "upload"

urlpatterns = [
    path("", views.upload_files, name="upload_files"),

]

if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
    )

onlineclass/models.py
from django.db import models
from upload.models import Document


# 최종 Commentor 서비스를 위한 모델
class Helper(models.Model):
	helper_id = models.AutoField(primary_key=True)
	doc_id = models.ForeignKey(Document, on_delete=models.CASCADE)
	helper_audio = models.FileField()
	helper_txt = models.FileField(null=True)
	helper_csv = models.FileField(null=True)

upload/models.py
from django.db import models

# Create your models here.

#교수자가 업로드하는 모델
class Document(models.Model):
	title = models.CharField(max_length = 200)
	videoFile = models.FileField(upload_to = "Uploaded_Files/")
	docFile = models.FileField(upload_to = "Uploaded_Files/")
	dateTiemOfUpload = models.DateTimeField(auto_now = True)

common/views.py
from django.shortcuts import render

# Create your views here.

onlineclass/views.py
import os

from upload.models import Document
from onlineclass.models import Helper

from django.http import HttpResponse
from django.template import loader

from django.http import FileResponse
from django.core.files.storage import FileSystemStorage


def show_origianl_video(request, doc_id):
    template = loader.get_template('onlineclass/original_video.html')

    doc = Document.objects.get(id=doc_id)
    context = {
        "doc": doc,
    }

    return HttpResponse(template.render(context, request))

def download_pdf(request, doc_id):
    doc = Document.objects.get(id=doc_id)

    file_path = doc.docFile.path
    fs = FileSystemStorage(file_path)

    set_filename = doc.title + " 강의자료.pdf"  # 파일명 지정
    print(set_filename)

    response = FileResponse(fs.open(file_path, 'rb'))
    response['Content-Disposition'] = 'attachment; filename=%s' %set_filename  # !!! 파일명 지정이 안되는 오류 발생 !!!
    return response


def execute_commentor(request, doc_id):
    template = loader.get_template('onlineclass/commentor.html')

    doc = Document.objects.get(id=doc_id)
    helper = Helper.objects.get(doc_id=doc_id)

    context = {
        "doc": doc,
        "helper": helper,
    }

    return HttpResponse(template.render(context, request))

def download_txt(request, doc_id):
    doc = Document.objects.get(id=doc_id)
    help = Helper.objects.get(doc_id=doc_id)

    file_path = help.helper_txt.path
    fs = FileSystemStorage(file_path)

    set_filename = doc.title + " 강의자료 해설파일.txt"  # 파일명 지정
    print(set_filename)

    response = FileResponse(fs.open(file_path, 'rb'))
    response['Content-Disposition'] = 'attachment; filename=%s' %set_filename  # !!! 파일명 지정이 안되는 오류 발생 !!!
    return response

upload/views.py
from upload.models import Document
from onlineclass.models import Helper

from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from upload.cmt_1_preprocess import execute_preprocess
from upload.cmt_2_mix import execute_mix

import time


def upload_files(request):
    if request.user.groups.exists():
        # 사용자 그룹 받아오기
        group = request.user.groups.all()[0].name

        # 교수자 그룹에 포함될 경우 렌더링
        if group == "professor_group":
            servicetime = 0
            progress = 0

            # 폼을 제출했을 경우 (POST) 그 외 (GET)
            if request.method == "POST":

                # Fetching the form data
                fileTitle = request.POST["fileTitle"]
                videoFile = request.FILES["videoFile"]
                docFile = request.FILES["docFile"]

                document = Document.objects.create(
                    title=fileTitle,
                    videoFile=videoFile,
                    docFile=docFile,
                )

                tmp_start = time.time()

                # 파일 저장경로(path) 불러오기
                path = document.docFile.path
                print("document.docFile.path: ", path)
                path = path[:-15]

                # commenter 서비스 실행
                execute_preprocess(path)
                execute_mix(path)

                servicetime = time.time() - tmp_start
                print(servicetime)

                helper = Helper.objects.create(
                    doc_id=document,
                    helper_audio=path + "mix\\mix.mp3",
                    helper_txt=path + "txt\\final_file.txt",
                    helper_csv=path + "transform_timeline_result.csv"
                )

                documents = Document.objects.all()

                progress = 100
                return render(request, "upload/upload_file.html", context={
                    "files": documents,
                    "sertime": servicetime * 10,
                    "progress_num": progress
                })

            else:
                documents = Document.objects.all()
                return render(request, "upload/upload_file.html", context={
                    "files": documents,
                    "sertime": 5000,
                    "progress_num": 0
                })

        # 학생 그룹에 포함될 경우 렌더링
        elif group == "student_group":

            template = loader.get_template('upload/view_file.html')
            documents = Document.objects.all()
            servicetime = time.time()

            context = {
                "files": documents,
                "sertime": servicetime
            }

            return HttpResponse(template.render(context, request))

templates/common/login.html
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
    	*{
		  margin: 0px;
		  padding: 0px;
		  text-decoration: none;
		  font-family:sans-serif;

		}

		body {
		  background: linear-gradient(to right,#81ecec,#6c5ce7,#81ecec);
		}

		.loginForm {
		  position:absolute;
		  width:300px;
		  height:350px;
		  padding: 30px;
		  background-color:#FFFFFF;
		  text-align:center;
		  top:50%;
		  left:50%;
		  transform: translate(-50%,-35%);
		  border-radius: 15px;
		}

		.loginForm h2{
            color: #3D3D3D;
            text-align: center;
            margin: 10px;
		}

		.idForm{
		  border-bottom: 2px solid #adadad;
		  margin: 30px;
		  padding: 10px 10px;
		}

		.passForm{
		  border-bottom: 2px solid #adadad;
		  margin: 30px;
		  padding: 10px 10px;
		}

		.id {
		  width: 100%;
		  border:none;
		  outline:none;
		  color: #636e72;
		  font-size:16px;
		  height:25px;
		  background: none;
		}

		.pw {
		  width: 100%;
		  border:none;
		  outline:none;
		  color: #636e72;
		  font-size:16px;
		  height:25px;
		  background: none;
		}

		.btn {
		  position:relative;
		  left:40%;
		  transform: translateX(-50%);
		  margin-bottom: 40px;
		  width:80%;
		  height:40px;
		  background: linear-gradient(125deg,#81ecec,#6c5ce7,#81ecec);
		  background-position: left;
		  background-size: 200%;
		  color:white;
		  font-weight: bold;
		  border:none;
		  cursor:pointer;
		  transition: 0.4s;
		  display:inline;
		}

		.btn:hover {
		  background-position: right;
		}

		.bottomText {
		  text-align: center;
		}

        #title {
            color: white;
            text-align: center;
            font-size: 40pt;
            margin-top:35px;
        }

        #subtitle {
            color: white;
            text-align: center;
            font-size: 15pt;
        }

    </style>
  </head>

  <body width="100%" height="100%">

    <br/>
    <h1 id="title">SNOWBOARD</h1>
    <h3 id="subtitle">with commentor service</h3>

  	<!-- 로그인 폼 시작 -->
    <form action="{% url 'common:login' %}" method="post" class="loginForm">
    	{% csrf_token %}
    	{% include "form_errors.html" %}

    	<h2>Login</h2>

    	<!--ID 입력-->
    	<div class="idForm">
    		<input type="text" class="id" placeholder="ID" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
    	</div>

    	<!--PW 입력-->
    	<div class="passForm">
    		<input type="password" class="pw" placeholder="PW" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
    	</div>

    	<!--로그인 버튼-->
    	<button type="submit" class="btn"> LOG IN </button>

    	<!--회원가입-->
    	<div class="bottomText">
    		Don't you have ID? <a href="#">sign up</a>
    	</div>
    </form>

  </body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/onlineclass/original_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>원본 강의 동영상 재생</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'original_video_style.css' %}">

</head>
<body>

    <nav>
        <h1 title="강의 제목">[VIDEO] {{ doc.title }}</h1>
        <button title="창 닫기" onclick = "window.close()">CLOSE</button>
    </nav>

    <section>
        <video src={{ doc.videoFile.url }} id="myVideo" controls loop preload></video>
    </section>

</body>
</html>

templates/upload/commentor.html
<style>
  form {
    position: absolute;
    left: 850px;
    top:100px;
    width: 150px;
    height: 70px;
  }
#fruits {
    position: absolute;
    left: 850px;
    top:200px;
    width: 150px;
    height: 100px;
  }
  #bt {
    padding: 0;
  border: none;
  background: none;
  }
  video{
    position: absolute;
    left: 20px;
    top:50px;
    width: 800px;
    height: 600px;
  }
  #butt{
    position: absolute;
    left: 20px;
    top:680px;
    width: 600px;
    height: 500px;
  }
  #prevSlide{
    margin-right:10px
  }
  #prevPlay{
    margin-right:10px
  }
  #videoPlay{
    margin-right:10px
  }
  #videoStop{
    margin-right:10px
  }
  #nextPlay{
    margin-right:10px
  }
  #nextSlide{
    margin-right:10px
  }

</style>
<!DOCTYPE html>
<html>
<head>
<title>title</title>
<!-- Bootstrap cdn 설정 -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>
<body>

  <script lang="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.9/xlsx.full.min.js"></script>

  <input type="file" id="id_file_upload" onchange="upload(event)"/>

  <ul id='fruits' tabindex="1"></ul>

  <form method="get" action="form-action.html">
    <label><input type="checkbox" name="option" value="전체 설명 생략"> 전체 설명 생략</label>
</form>
<!-- audio와 video 설정 -->
<video src="C:\Users\SM-PC\Desktop\Commentor\UIUX\lecture_audio.mp3" id="myVideo" width='450' height='360'
poster='C:\Users\SM-PC\Desktop\Commentor\UIUX\capture_FA\003.jpg' controls autoplay loop preload></video>
<br />

<class id=butt>
<button id="prevSlide">이전 슬라이드</button>
<button id="prevPlay">6초 전</button>
<button id="videoPlay">재생</button>
<button id="videoStop">일시정지</button>
<button id="nextPlay">6초 후</button>
<button id="nextSlide">다음 슬라이드</button>
</class>



<script>
// video 오브젝트를 취득함.
var video = document.getElementById("myVideo");

var vid = document.getElementById("myVideo");
var arr = new Array();

//6초 전 클릭
$("#prevPlay").on("click", function() {
video.currentTime-=6;
});

//재생 클릭
$("#videoPlay").on("click", function() {
video.play();
});

//일시정지 클릭
$("#videoStop").on("click", function() {
video.pause();
});

//6초 후 클릭
$("#nextPlay").on("click", function() {
video.currentTime+=6;
});

//이전 슬라이드
$("#prevSlide").on("click", function() {
  var time_cur = video.currentTime;
  time_cur *= 1;
  for(k = 0; k < arr.length-1; k++) {

    if(arr[k]<= time_cur && time_cur < arr[k+1]){
      video.currentTime = arr[k];
      break;
    }
    if(time_cur > arr[arr.length-1]){
      video.currentTime = arr[arr.length-1];
      break;
    }
  }
});

//다음 슬라이드
$("#nextSlide").on("click", function() {
  var time_cur = video.currentTime;
  time_cur *= 1;
  //console.log(time_cur);
  //console.log(arr.length);
  //console.log(video.duration);
  for(k = 0; k < arr.length-1; k++) {

    if(arr[k]<= time_cur && time_cur < arr[k+1]){
      video.currentTime = arr[k+1];
      console.log(video.currentTime);
      break;
    }
    if(time_cur > arr[arr.length-1]){
      video.currentTime = video.duration;
      break;
    }
  }
});

function getCurTime() {
    alert(vid.currentTime);
}

function upload(event){
  var input = event.target;
  var reader = new FileReader();
  var objKeyArr;


  reader.onload = function(){
    var fdata = reader.result;
    var read_buffer = XLSX.read(fdata, {type : 'binary'});

    read_buffer.SheetNames.forEach(function(sheetName){
      var rowdata =XLSX.utils.sheet_to_json(read_buffer.Sheets[sheetName]);
      //console.log(JSON.stringify(rowdata));
      objKeyArr = Object.keys(rowdata);

      for(C = 0; C < objKeyArr.length; ++C) {
        console.log("time : "+ JSON.stringify(rowdata[C].time));
        arr[C] = JSON.stringify(rowdata[C].time);
      }
      for(B = 0; B < objKeyArr.length; ++B) {

        const addValue = B;

        // 2. 추가할 li element 생성
        // 2-1. 추가할 li element 생성
        const li = document.createElement("li");

        // 2-2. li에 id 속성 추가
        li.setAttribute('id',addValue);
        li.setAttribute('tabindex', addValue+2);
        li.setAttribute('onkeypress',"JavaScript:press(this.form)")

        // 2-3. li에 text node 추가
        const textNode = document.createTextNode(B+1+"번 슬라이드");
        li.appendChild(textNode);

        // 3. 생성된 li를 ol에 추가
        document
          .getElementById('fruits')
          .appendChild(li);

      }
    })
    // var u_list = document.getElementById('3');
    // console.log(u_list);
  //  $(document).ready(function(){
      //$('li').onclick(function(index){
      $('li').on("click", function() {
        console.log($('li').index(this)+1);
        var idd= $('li').index(this)+1;

        for(A = 0; A < objKeyArr.length; ++A)
        {
          if(idd == A+1)
          {
            tt = Number(arr[A]);
            tt *=1;
            vid.currentTime=tt;
          }
        }


      });
  //  });


  };
  reader.readAsBinaryString(input.files[0]);

}

</script>
</body>
</html>

templates/upload/upload_file.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Django File Upload</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'upload_style.css' %}">

</head>
<body>
    <nav class="navbar">
        <button class="navbar_logo" onclick = "location.href = '{% url 'upload:upload_files' %}' " title="메인 페이지 재로드 버튼">SNOWBOARD</button>
        <ul>
            <li><button class="username_design" title="마이페이지 버튼">Welcome, {{ user.username }} !</button></li>
            <li><button class="logout_design" onclick = "location.href = '{% url 'common:login' %}' " title="로그아웃 버튼">LOGOUT</button></li>
        </ul>
    </nav>

    <aside>
        <div class="form_box">
            <div id="form_title">
                <div style="padding: 10px; font-size: 15pt; font-weight: bolder; text-align: center; display: table-cell; vertical-align: middle;">Submit a lecture file</div>
            </div>
            <form id="file_form" action="{% url 'upload:upload_files' %}" method="POST" enctype="multipart/form-data">
                <div id="form_inner_box">
                    <div class="form_text">Lecture Title</div>
                    <input class="text_input" type="text" name="fileTitle" placeholder="Enter a title">
                    <div class="form_text">Choose Lecture Video(.mp4)</div>
                    <input class="text_input" type="file" name="videoFile">
                    <div class="form_text">Choose Lecture Material(.pdf)</div>
                    <input class="text_input" type="file" name="docFile">
                    {% csrf_token %}
                </div>
                <button id="submit_bnt" type="submit" value="Upload" onclick="move()">Upload</button>
            </form>
        </div>
    </aside>

    <section>
        <h1>Task Loading</h1>

        <div id="myProgress">
        <div id="myBar">
            <div id="label">{{progress_num}}%</div>
        </div>
        </div>

        <h3 id="pro_text">진행상태 {{progress_num}}%</h3>
        <p>{{sertime}}</p>
        <p>{{user_name}}</p>

        <h1>Lecture list uploaded to server</h1>

        <table>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Video File Path</th>
                <th>Doc File Path</th>
                <th>Upload Date & Time</th>
            </tr>
            {% for file in files %}
                <tr>
                    <td>{{ file.id }}</td>
                    <td>{{ file.title }}</td>
                    <td>{{ file.videoFile.url }}</td>
                    <td>{{ file.docFile.url }}</td>
                    <td>{{ file.dateTimeOfUpload }}</td>
                </tr>
            {% endfor %}
        </table>
    </section>

<script>
    function move() {
        var elem = document.getElementById("myBar");
        var pro_text = document.getElementById("pro_text");
        var width = 0;
        var id = setInterval(frame, {{sertime}});
        function frame() {
            if (width >= 100) {
            clearInterval(id);
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 완료되었습니다.';
            }
            else if(width <= 10){
            width++;
            elem.style.width = width + '%';
            document.getElementById("label").innerHTML = width * 1  + '%';
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 파일 업로드 요청을 하고 있습니다.';
            }
            else if(width <= 20){
            width++;
            elem.style.width = width + '%';
            document.getElementById("label").innerHTML = width * 1  + '%';
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 파일을 저장하고 있습니다.';
            }
            else if(width <= 70){
            width++;
            elem.style.width = width + '%';
            document.getElementById("label").innerHTML = width * 1  + '%';
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 저장된 파일로 commentor 서비스를 실행하고 있습니다.';
            }
            else if(width <= 85){
            width++;
            elem.style.width = width + '%';
            document.getElementById("label").innerHTML = width * 1  + '%';
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 부가 파일들 저장하고 있습니다.';
            }
            else if(width < 100){
            width++;
            elem.style.width = width + '%';
            document.getElementById("label").innerHTML = width * 1  + '%';
            document.getElementById("pro_text").innerHTML = '진행상태 ' + width * 1  + '% : 부가 파일들 경로를 db에 저장하고 있습니다.';
            }
        }
    }

</script>

</body>
</html>

templates/upload/view_file.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Django File Upload</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'view_style.css' %}">

    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>

</head>
<body>
    <nav class="navbar">
        <button class="navbar_logo" onclick = "location.href = '{% url 'upload:upload_files' %}' " title="메인 페이지 재로드 버튼">SNOWBOARD</button>
        <ul>
            <li><button class="username_design" title="마이페이지 버튼">Welcome, {{ user.username }} !</button></li>
            <li><button class="logout_design" onclick = "location.href = '{% url 'common:login' %}' " title="로그아웃 버튼">LOGOUT</button></li>
        </ul>
    </nav>

    <div class="introduce_box">
        <span><i class="fas fa-user-circle fa-5x"></i></span>
        <div class="introduce_box_info">
            <div class="introduce_box_classname">UI/UX 설계</div>
            <div class="introduce_box_profname">임순범 교수님</div>
        </div>
    </div>

    <aside>
        <div class="aside_category">강의실 홈</div>
            <ul class="first_list">
                <li>강의정보</li>
                <ul class="inner_list">
                    <li>강의계획서</li>
                    <li>참여자목록</li>
                </ul>
                <li>성적/출석관리</li>
                <ul class="inner_list">
                    <li>온라인출석부</li>
                    <li>성적부</li>
                </ul>
                <li>수강생 알림</li>
                <ul class="inner_list">
                    <li>쪽지 보내기</li>
                </ul>
                <li>강좌 관리</li>
                <ul class="inner_list">
                    <li>팀원</li>
                </ul>
            </ul>
        <div class="aside_category">학습활동</div>
            <ul class="second_list">
                <li><i class="fas fa-save" style="color: #71B5CC"></i> &nbsp; 파일</li>
                <li><i class="far fa-play-circle" style="color: #8B8884"></i> &nbsp; 콘텐츠메이커</li>
                <li><i class="fas fa-sticky-note" style="color: #EA665A"></i> &nbsp; 과제</li>
                <li><i class="fas fa-clipboard" style="color: #F3994E"></i> &nbsp; 게시판</li>
                <li><i class="fas fa-link" style="color: #679ACD"></i> &nbsp; URL링크</li>
                <li><i class="fas fa-check-circle" style="color: #C064A9"></i> &nbsp; 퀴즈</li>
                <li><i class="fas fa-user-friends" style="color: #F5BB47"></i> &nbsp; 토론</li>
                <li><i class="fas fa-folder" style="color: #F6B65C"></i> &nbsp; 폴더</li>
                <li><i class="fas fa-pencil-alt" style="color: #F07A7A"></i> &nbsp; 표지</li>
            </ul>
    </aside>

    <section>
        {% for file in files %}
            <div class="class_box">

                <div class="class_title_box" title="강의제목: {{ file.title }}">
                    <div class="class_title">{{ file.title }}</div>
                </div>

                <div class="class_inner_box">
                    <a href="javascript:open_Origianl_Win({{ file.id }})" title="강의 동영상 재생">
                        <i class="far fa-play-circle"></i> 강의 동영상 재생
                    </a>
                    <a href="/onlineclass/pdf_download/{{ file.id }}/" target="_blank" title="강의 자료 다운로드">
                        <i class="fas fa-file-pdf"></i> 강의 자료 다운로드
                    </a>
                    <a href="javascript:open_Cmt_Win({{ file.id }})" title="해설 비디오 파일 재생">
                        <i class="far fa-play-circle"></i> 해설 비디오 파일 재생
                    </a>
                    <a href="/onlineclass/txt_download/{{ file.id }}/" target="_blank" title="강의자료 해설 파일 다운로드">
                        <i class="fas fa-file-alt"></i> 강의자료 해설 파일 다운로드
                    </a>
                </div>

            </div>
        {% endfor %}
    </section>

    <script language="javascript" type="text/javascript">
        function open_Origianl_Win(file_id){
            window.open(
                "/onlineclass/original_video/"+file_id+"/",
                "원본 강의 재생",
                "left=120, top=5, width=1280, height=750, location=no, toolbar=no, menubar=no, scrollbars=no, resizable=yes"
            );
        }
        function open_Cmt_Win(file_id){
            window.open(
                "/onlineclass/commentor/"+file_id+"/",
                "해설 강의 재생",
                "left=120, top=25, width=1280, height=700, location=no, toolbar=no, menubar=no, scrollbars=no, resizable=yes"
            );
        }
    </script>

</body>
</html>